[workspace]
members = [
    "crates/app",
    "crates/front",
    "crates/shared",
    "crates/server",
    "crates/bot"]
resolver = "2"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[workspace.dependencies]
leptos = { version = "0.7.8", default-features = false, features = ["nightly"] }
leptos_meta = { version = "0.7.8", default-features = false }
leptos_router = { version = "0.7.8", default-features = false, features = ["nightly"] }
leptos_dom = { version = "0.7.8", default-features = false }
leptos_actix = { version = "0.7.8" }

serde = { version = "1.0.219", feature = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.8.5", features = ["sqlite", "runtime-tokio-rustls", "chrono", "macros"] }
config = { version = "0.15.11" }

# See https://github.com/leptos-rs/cargo-leptos for documentation of all the parameters.

# A leptos project defines which workspace members
# that are used together frontend (lib) & server (bin)
[[workspace.metadata.leptos]]
name = "remote-bot"
bin-package = "remote-bot-server"
lib-package = "remote-bot-front"
assets-dir = "assets"
tailwind-input-file = "assets/styles/index.css"
site-root = "target/site"

[workspace.metadata.crane]
name = "remote-bot"
