[package]
name = "remote-bot-front"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
remote-bot-app = { path = "../app", features = ["hydrate"] }
leptos = { workspace = true, features = ["hydrate"] }

console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.100"
